name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
categories:
  - title: "💥 Breaking Change 💥"
    labels:
      - "breaking-change"
  - title: "⚡ Enhancements ⚡"
    labels:
      - "enhancement"
  - title: "✨ New Features ✨"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔩 Dependency 🔩"
    labels:
      - "dependencies"
    collapse-after: 3
  - title: "🔧 Maintenance 🔧"
    labels:
      - "chore"
      - "ci"
    collapse-after: 3
  - title: "🎓 Code Quality 🎓"
    labels:
      - "code-quality"
  - title: "🎨 Styling 🎨"
    labels:
      - "style"
  - title: "📝 Documentation 📝"
    labels:
      - "documentation"

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/ha-smartthings-card/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/ha-smartthings-card/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/firstof9/ha-smartthings-card/issues)
