name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
categories:
  - title: "💥 Breaking Change 💥"
    labels:
      - "breaking-change"
    exclusive: true
  - title: "⚡ Enhancements ⚡"
    labels:
      - "enhancement"
    exclusive: true
  - title: "✨ New Features ✨"
    labels:
      - "feature"
    exclusive: true
  - title: "🐛 Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
    exclusive: true
  - title: "🎨 Styling 🎨"
    labels:
      - "style"
    exclusive: true    
  - title: "🔩 Dependency 🔩"
    labels:
      - "dependencies"
    collapse-after: 1
    exclusive: true
  - title: "🔧 Maintenance 🔧"
    labels:
      - "chore"
      - "ci"
    collapse-after: 1
    exclusive: true
  - title: "🎓 Code Quality 🎓"
    labels:
      - "code-quality"
    exclusive: true
  - title: "📝 Documentation 📝"
    labels:
      - "documentation"
    collapse-after: 1
    exclusive: true

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/ha-smartthings-card/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/ha-smartthings-card/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/firstof9/ha-smartthings-card/issues)

autolabeler:
  - label: "feature"
    title:
      - "/^feat/i"
  - label: "bugfix"
    title:
      - "/^fix/i"
  - label: "chore"
    title:
      - "/^chore/i"
  - label: "ci"
    title:
      - "/^ci/i"
    files:
      - ".github/**/*"
  - label: "style"
    title:
      - "/^style/i"
    files:
      - "src/styles/**/*"
  - label: "documentation"
    title:
      - "/^docs/i"
    files:
      - "README.md"
      - "images/**/*"
      - "screenshots/**/*"
  - label: "enhancement"
    title:
      - "/^refactor/i"
  - label: "code-quality"
    title:
      - "/^tests/i"
    files:
      - "test/**/*"
  - label: "dependencies"
    title:
      - "/^build\\(deps\\)/i"
      - "/^chore\\(deps\\)/i"

