import fs from 'fs';
import path from 'path';

const imagesDir = './images';
const outputFile = './src/assets.ts';

function generateAssets() {
  let content = '/* This file is auto-generated by generate-assets.js */\n\n';
  const appliances = fs.readdirSync(imagesDir).filter(f => fs.statSync(path.join(imagesDir, f)).isDirectory());

  const assetMap = {};

  appliances.forEach(appliance => {
    const applianceDir = path.join(imagesDir, appliance);
    const images = fs.readdirSync(applianceDir).filter(f => f.endsWith('.png'));
    
    assetMap[appliance] = {};
    
    images.forEach(image => {
      const varName = `${appliance}_${image.replace(/[^a-z0-9]/gi, '_')}`.toLowerCase();
      content += `import ${varName} from '../images/${appliance}/${image}';\n`;
      assetMap[appliance][image] = varName;
    });
  });

  content += '\nexport const ASSETS: Record<string, Record<string, string>> = {\n';
  for (const [appliance, images] of Object.entries(assetMap)) {
    content += `  '${appliance}': {\n`;
    for (const [image, varName] of Object.entries(images)) {
      content += `    '${image}': ${varName},\n`;
    }
    content += '  },\n';
  }
  content += '};\n';

  fs.writeFileSync(outputFile, content);
  console.log(`Generated ${outputFile}`);
}

generateAssets();
