/* This file is auto-generated by generate-assets.js */

import dishwasher_appliance_png from '../images/dishwasher/appliance.png';
import dishwasher_dry_plate_on_png from '../images/dishwasher/dry-plate-on.png';
import dishwasher_dry_plate_png from '../images/dishwasher/dry-plate.png';
import dishwasher_hass_samsung_dishwasher_card_bg_steel_png from '../images/dishwasher/hass-samsung-dishwasher-card-bg-steel.png';
import dishwasher_lock_on_png from '../images/dishwasher/lock-on.png';
import dishwasher_lock_png from '../images/dishwasher/lock.png';
import dishwasher_prewash_on_png from '../images/dishwasher/prewash-on.png';
import dishwasher_prewash_png from '../images/dishwasher/prewash.png';
import dishwasher_rinse_plate_on_png from '../images/dishwasher/rinse-plate-on.png';
import dishwasher_rinse_plate_png from '../images/dishwasher/rinse-plate.png';
import dishwasher_sensing_on_png from '../images/dishwasher/sensing-on.png';
import dishwasher_sensing_png from '../images/dishwasher/sensing.png';
import dishwasher_wash_plate_on_png from '../images/dishwasher/wash-plate-on.png';
import dishwasher_wash_plate_png from '../images/dishwasher/wash-plate.png';
import dishwasher_wifi_on_png from '../images/dishwasher/wifi-on.png';
import dishwasher_wifi_png from '../images/dishwasher/wifi.png';
import dryer_appliance_png from '../images/dryer/appliance.png';
import dryer_cool_on_png from '../images/dryer/cool-on.png';
import dryer_cool_png from '../images/dryer/cool.png';
import dryer_dry_on_png from '../images/dryer/dry-on.png';
import dryer_dry_png from '../images/dryer/dry.png';
import dryer_hass_samsung_dryer_card_bg_black_png from '../images/dryer/hass-samsung-dryer-card-bg-black.png';
import dryer_lock_on_png from '../images/dryer/lock-on.png';
import dryer_lock_png from '../images/dryer/lock.png';
import dryer_wifi_on_png from '../images/dryer/wifi-on.png';
import dryer_wifi_png from '../images/dryer/wifi.png';
import microwave_appliance_png from '../images/microwave/appliance.png';
import microwave_autocook_off_png from '../images/microwave/autocook-off.png';
import microwave_autocook_png from '../images/microwave/autocook.png';
import microwave_bake_on_png from '../images/microwave/bake-on.png';
import microwave_bake_png from '../images/microwave/bake.png';
import microwave_convection_on_png from '../images/microwave/convection-on.png';
import microwave_convection_png from '../images/microwave/convection.png';
import microwave_conventional_on_png from '../images/microwave/conventional-on.png';
import microwave_conventional_png from '../images/microwave/conventional.png';
import microwave_cooking_on_png from '../images/microwave/cooking-on.png';
import microwave_cooking_png from '../images/microwave/cooking.png';
import microwave_grill_on_png from '../images/microwave/grill-on.png';
import microwave_grill_png from '../images/microwave/grill.png';
import microwave_hass_samsung_microwave_card_bg_black_png from '../images/microwave/hass-samsung-microwave-card-bg-black.png';
import microwave_hot_blast_on_png from '../images/microwave/hot_blast-on.png';
import microwave_hot_blast_png from '../images/microwave/hot_blast.png';
import microwave_microwave_on_png from '../images/microwave/microwave-on.png';
import microwave_microwave_png from '../images/microwave/microwave.png';
import microwave_rinse_on_png from '../images/microwave/rinse-on.png';
import microwave_rinse_png from '../images/microwave/rinse.png';
import microwave_steam_on_png from '../images/microwave/steam-on.png';
import microwave_steam_png from '../images/microwave/steam.png';
import oven_appliance_png from '../images/oven/appliance.png';
import oven_bake_on_png from '../images/oven/bake-on.png';
import oven_bake_png from '../images/oven/bake.png';
import oven_convection_on_png from '../images/oven/convection-on.png';
import oven_convection_png from '../images/oven/convection.png';
import oven_conventional_on_png from '../images/oven/conventional-on.png';
import oven_conventional_png from '../images/oven/conventional.png';
import oven_cooking_on_png from '../images/oven/cooking-on.png';
import oven_cooking_png from '../images/oven/cooking.png';
import oven_grill_on_png from '../images/oven/grill-on.png';
import oven_grill_png from '../images/oven/grill.png';
import oven_hot_blast_on_png from '../images/oven/hot_blast-on.png';
import oven_hot_blast_png from '../images/oven/hot_blast.png';
import oven_microwave_on_png from '../images/oven/microwave-on.png';
import oven_microwave_png from '../images/oven/microwave.png';
import oven_rinse_on_png from '../images/oven/rinse-on.png';
import oven_rinse_png from '../images/oven/rinse.png';
import oven_steam_on_png from '../images/oven/steam-on.png';
import oven_steam_png from '../images/oven/steam.png';
import refrigerator_appliance_png from '../images/refrigerator/appliance.png';
import refrigerator_freezer_temp_png from '../images/refrigerator/freezer-temp.png';
import refrigerator_fridge_temp_png from '../images/refrigerator/fridge-temp.png';
import refrigerator_hass_samsung_fridge_card_bg_black_png from '../images/refrigerator/hass-samsung-fridge-card-bg-black.png';
import refrigerator_icemaker_off_png from '../images/refrigerator/icemaker_off.png';
import refrigerator_icemaker_on_png from '../images/refrigerator/icemaker_on.png';
import washer_appliance_png from '../images/washer/appliance.png';
import washer_hass_samsung_washer_card_bg_black_png from '../images/washer/hass-samsung-washer-card-bg-black.png';
import washer_lock_on_png from '../images/washer/lock-on.png';
import washer_lock_png from '../images/washer/lock.png';
import washer_rinse_on_png from '../images/washer/rinse-on.png';
import washer_rinse_png from '../images/washer/rinse.png';
import washer_spin_on_png from '../images/washer/spin-on.png';
import washer_spin_png from '../images/washer/spin.png';
import washer_wash_on_png from '../images/washer/wash-on.png';
import washer_wash_png from '../images/washer/wash.png';
import washer_weight_sensing_on_png from '../images/washer/weight_sensing-on.png';
import washer_weight_sensing_png from '../images/washer/weight_sensing.png';
import washer_wifi_on_png from '../images/washer/wifi-on.png';
import washer_wifi_png from '../images/washer/wifi.png';

export const ASSETS: Record<string, Record<string, string>> = {
  'dishwasher': {
    'appliance.png': dishwasher_appliance_png,
    'dry-plate-on.png': dishwasher_dry_plate_on_png,
    'dry-plate.png': dishwasher_dry_plate_png,
    'hass-samsung-dishwasher-card-bg-steel.png': dishwasher_hass_samsung_dishwasher_card_bg_steel_png,
    'lock-on.png': dishwasher_lock_on_png,
    'lock.png': dishwasher_lock_png,
    'prewash-on.png': dishwasher_prewash_on_png,
    'prewash.png': dishwasher_prewash_png,
    'rinse-plate-on.png': dishwasher_rinse_plate_on_png,
    'rinse-plate.png': dishwasher_rinse_plate_png,
    'sensing-on.png': dishwasher_sensing_on_png,
    'sensing.png': dishwasher_sensing_png,
    'wash-plate-on.png': dishwasher_wash_plate_on_png,
    'wash-plate.png': dishwasher_wash_plate_png,
    'wifi-on.png': dishwasher_wifi_on_png,
    'wifi.png': dishwasher_wifi_png,
  },
  'dryer': {
    'appliance.png': dryer_appliance_png,
    'cool-on.png': dryer_cool_on_png,
    'cool.png': dryer_cool_png,
    'dry-on.png': dryer_dry_on_png,
    'dry.png': dryer_dry_png,
    'hass-samsung-dryer-card-bg-black.png': dryer_hass_samsung_dryer_card_bg_black_png,
    'lock-on.png': dryer_lock_on_png,
    'lock.png': dryer_lock_png,
    'wifi-on.png': dryer_wifi_on_png,
    'wifi.png': dryer_wifi_png,
  },
  'general': {
  },
  'microwave': {
    'appliance.png': microwave_appliance_png,
    'autocook-off.png': microwave_autocook_off_png,
    'autocook.png': microwave_autocook_png,
    'bake-on.png': microwave_bake_on_png,
    'bake.png': microwave_bake_png,
    'convection-on.png': microwave_convection_on_png,
    'convection.png': microwave_convection_png,
    'conventional-on.png': microwave_conventional_on_png,
    'conventional.png': microwave_conventional_png,
    'cooking-on.png': microwave_cooking_on_png,
    'cooking.png': microwave_cooking_png,
    'grill-on.png': microwave_grill_on_png,
    'grill.png': microwave_grill_png,
    'hass-samsung-microwave-card-bg-black.png': microwave_hass_samsung_microwave_card_bg_black_png,
    'hot_blast-on.png': microwave_hot_blast_on_png,
    'hot_blast.png': microwave_hot_blast_png,
    'microwave-on.png': microwave_microwave_on_png,
    'microwave.png': microwave_microwave_png,
    'rinse-on.png': microwave_rinse_on_png,
    'rinse.png': microwave_rinse_png,
    'steam-on.png': microwave_steam_on_png,
    'steam.png': microwave_steam_png,
  },
  'oven': {
    'appliance.png': oven_appliance_png,
    'bake-on.png': oven_bake_on_png,
    'bake.png': oven_bake_png,
    'convection-on.png': oven_convection_on_png,
    'convection.png': oven_convection_png,
    'conventional-on.png': oven_conventional_on_png,
    'conventional.png': oven_conventional_png,
    'cooking-on.png': oven_cooking_on_png,
    'cooking.png': oven_cooking_png,
    'grill-on.png': oven_grill_on_png,
    'grill.png': oven_grill_png,
    'hot_blast-on.png': oven_hot_blast_on_png,
    'hot_blast.png': oven_hot_blast_png,
    'microwave-on.png': oven_microwave_on_png,
    'microwave.png': oven_microwave_png,
    'rinse-on.png': oven_rinse_on_png,
    'rinse.png': oven_rinse_png,
    'steam-on.png': oven_steam_on_png,
    'steam.png': oven_steam_png,
  },
  'refrigerator': {
    'appliance.png': refrigerator_appliance_png,
    'freezer-temp.png': refrigerator_freezer_temp_png,
    'fridge-temp.png': refrigerator_fridge_temp_png,
    'hass-samsung-fridge-card-bg-black.png': refrigerator_hass_samsung_fridge_card_bg_black_png,
    'icemaker_off.png': refrigerator_icemaker_off_png,
    'icemaker_on.png': refrigerator_icemaker_on_png,
  },
  'washer': {
    'appliance.png': washer_appliance_png,
    'hass-samsung-washer-card-bg-black.png': washer_hass_samsung_washer_card_bg_black_png,
    'lock-on.png': washer_lock_on_png,
    'lock.png': washer_lock_png,
    'rinse-on.png': washer_rinse_on_png,
    'rinse.png': washer_rinse_png,
    'spin-on.png': washer_spin_on_png,
    'spin.png': washer_spin_png,
    'wash-on.png': washer_wash_on_png,
    'wash.png': washer_wash_png,
    'weight_sensing-on.png': washer_weight_sensing_on_png,
    'weight_sensing.png': washer_weight_sensing_png,
    'wifi-on.png': washer_wifi_on_png,
    'wifi.png': washer_wifi_png,
  },
};
