/* This file is auto-generated by generate-assets.js */

import dishwasher_dry_plate_on_png from '../images/dishwasher/dry-plate-on.png';
import dishwasher_dry_plate_png from '../images/dishwasher/dry-plate.png';
import dishwasher_hass_samsung_dishwasher_card_bg_steel_png from '../images/dishwasher/hass-samsung-dishwasher-card-bg-steel.png';
import dishwasher_lock_on_png from '../images/dishwasher/lock-on.png';
import dishwasher_lock_png from '../images/dishwasher/lock.png';
import dishwasher_prewash_on_png from '../images/dishwasher/prewash-on.png';
import dishwasher_prewash_png from '../images/dishwasher/prewash.png';
import dishwasher_rinse_plate_on_png from '../images/dishwasher/rinse-plate-on.png';
import dishwasher_rinse_plate_png from '../images/dishwasher/rinse-plate.png';
import dishwasher_sensing_on_png from '../images/dishwasher/sensing-on.png';
import dishwasher_sensing_png from '../images/dishwasher/sensing.png';
import dishwasher_wash_plate_on_png from '../images/dishwasher/wash-plate-on.png';
import dishwasher_wash_plate_png from '../images/dishwasher/wash-plate.png';
import dishwasher_wifi_on_png from '../images/dishwasher/wifi-on.png';
import dishwasher_wifi_png from '../images/dishwasher/wifi.png';
import dryer_cool_on_png from '../images/dryer/cool-on.png';
import dryer_cool_png from '../images/dryer/cool.png';
import dryer_dry_on_png from '../images/dryer/dry-on.png';
import dryer_dry_png from '../images/dryer/dry.png';
import dryer_hass_samsung_dryer_card_bg_black_png from '../images/dryer/hass-samsung-dryer-card-bg-black.png';
import dryer_lock_on_png from '../images/dryer/lock-on.png';
import dryer_lock_png from '../images/dryer/lock.png';
import dryer_wifi_on_png from '../images/dryer/wifi-on.png';
import dryer_wifi_png from '../images/dryer/wifi.png';
import microwave_autocook_off_png from '../images/microwave/autocook-off.png';
import microwave_autocook_png from '../images/microwave/autocook.png';
import microwave_hass_samsung_microwave_card_bg_black_png from '../images/microwave/hass-samsung-microwave-card-bg-black.png';
import microwave_microwave_png from '../images/microwave/microwave.png';
import refrigerator_freezer_temp_png from '../images/refrigerator/freezer-temp.png';
import refrigerator_fridge_temp_png from '../images/refrigerator/fridge-temp.png';
import refrigerator_hass_samsung_fridge_card_bg_black_png from '../images/refrigerator/hass-samsung-fridge-card-bg-black.png';
import refrigerator_icemaker_off_png from '../images/refrigerator/icemaker_off.png';
import refrigerator_icemaker_on_png from '../images/refrigerator/icemaker_on.png';
import washer_hass_samsung_washer_card_bg_black_png from '../images/washer/hass-samsung-washer-card-bg-black.png';
import washer_lock_on_png from '../images/washer/lock-on.png';
import washer_lock_png from '../images/washer/lock.png';
import washer_rinse_on_png from '../images/washer/rinse-on.png';
import washer_rinse_png from '../images/washer/rinse.png';
import washer_sensing_on_png from '../images/washer/sensing-on.png';
import washer_sensing_png from '../images/washer/sensing.png';
import washer_spin_on_png from '../images/washer/spin-on.png';
import washer_spin_png from '../images/washer/spin.png';
import washer_wash_on_png from '../images/washer/wash-on.png';
import washer_wash_png from '../images/washer/wash.png';
import washer_wifi_on_png from '../images/washer/wifi-on.png';
import washer_wifi_png from '../images/washer/wifi.png';

export const ASSETS: Record<string, Record<string, string>> = {
  'dishwasher': {
    'dry-plate-on.png': dishwasher_dry_plate_on_png,
    'dry-plate.png': dishwasher_dry_plate_png,
    'hass-samsung-dishwasher-card-bg-steel.png': dishwasher_hass_samsung_dishwasher_card_bg_steel_png,
    'lock-on.png': dishwasher_lock_on_png,
    'lock.png': dishwasher_lock_png,
    'prewash-on.png': dishwasher_prewash_on_png,
    'prewash.png': dishwasher_prewash_png,
    'rinse-plate-on.png': dishwasher_rinse_plate_on_png,
    'rinse-plate.png': dishwasher_rinse_plate_png,
    'sensing-on.png': dishwasher_sensing_on_png,
    'sensing.png': dishwasher_sensing_png,
    'wash-plate-on.png': dishwasher_wash_plate_on_png,
    'wash-plate.png': dishwasher_wash_plate_png,
    'wifi-on.png': dishwasher_wifi_on_png,
    'wifi.png': dishwasher_wifi_png,
  },
  'dryer': {
    'cool-on.png': dryer_cool_on_png,
    'cool.png': dryer_cool_png,
    'dry-on.png': dryer_dry_on_png,
    'dry.png': dryer_dry_png,
    'hass-samsung-dryer-card-bg-black.png': dryer_hass_samsung_dryer_card_bg_black_png,
    'lock-on.png': dryer_lock_on_png,
    'lock.png': dryer_lock_png,
    'wifi-on.png': dryer_wifi_on_png,
    'wifi.png': dryer_wifi_png,
  },
  'general': {
  },
  'microwave': {
    'autocook-off.png': microwave_autocook_off_png,
    'autocook.png': microwave_autocook_png,
    'hass-samsung-microwave-card-bg-black.png': microwave_hass_samsung_microwave_card_bg_black_png,
    'microwave.png': microwave_microwave_png,
  },
  'oven': {
  },
  'refrigerator': {
    'freezer-temp.png': refrigerator_freezer_temp_png,
    'fridge-temp.png': refrigerator_fridge_temp_png,
    'hass-samsung-fridge-card-bg-black.png': refrigerator_hass_samsung_fridge_card_bg_black_png,
    'icemaker_off.png': refrigerator_icemaker_off_png,
    'icemaker_on.png': refrigerator_icemaker_on_png,
  },
  'washer': {
    'hass-samsung-washer-card-bg-black.png': washer_hass_samsung_washer_card_bg_black_png,
    'lock-on.png': washer_lock_on_png,
    'lock.png': washer_lock_png,
    'rinse-on.png': washer_rinse_on_png,
    'rinse.png': washer_rinse_png,
    'sensing-on.png': washer_sensing_on_png,
    'sensing.png': washer_sensing_png,
    'spin-on.png': washer_spin_on_png,
    'spin.png': washer_spin_png,
    'wash-on.png': washer_wash_on_png,
    'wash.png': washer_wash_png,
    'wifi-on.png': washer_wifi_on_png,
    'wifi.png': washer_wifi_png,
  },
};
